#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
bspc monitor -d I II III IV V VI VII VIII IX X

############Window Settings ####################
bspc config border_width             2
bspc config window_gap               5
bspc config split_ratio              0.50
bspc config borderless_monocle       false
bspc config gapless_monocle          false
# bspc config top_padding 	         20

########## Border Colors #################
bspc config focused_border_color   "#df2d52"
bspc config normal_border_color    "#33292b"

######### Program settings ################
dunst &

######### Other Settings ################
# xsetroot -cursor_name left_ptr &
xbacklight -set 70
# xinput set-prop 12 309 1
