#! /bin/sh

BG=$(xrdb -query | grep 'background:'| awk '{print $NF}')
FOCUS=$(xrdb -query | grep 'wmColor3:'| awk '{print $NF}')
ACTIVE=$(xrdb -query | grep 'wmColor4:'| awk '{print $NF}')

pgrep -x sxhkd >/dev/null || sxhkd &

export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

$HOME/.config/polybar/launch.sh

bspc monitor DP-0 -d 1 3 5 7 9
bspc monitor DVI-D-0 -d 2 4 6 8 10

############ Window Settings #################
bspc config border_width            2
bspc config window_gap              5
bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config gapless_monocle         false

############ Border Colors #################
bspc config focused_border_color   "$FOCUS"
bspc config normal_border_color    "$BG"
bspc config active_border_color    "$ACTIVE"
bspc config presel_feedback_color  "$FOCUS"

############ Rules #################
# xprop |awk '/WM_CLASS/{print $4}'
bspc rule -a '*:pavucontrol' state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a '*:keepassxc' state=floating
bspc rule -a '*:telegram-desktop' state=floating
bspc rule -a '*:gscreenshot' state=floating
bspc rule -a 'NoiseTorch' state=floating
bspc rule -a 'VK' state=floating
bspc rule -a '*:gnome-calendar' state=floating
bspc rule -a '*:galculator' state=floating
bspc rule -a '*:zoom' state=floating
bspc rule -a '*:discord' state=floating
bspc rule -a '*:whatsapp-for-linux' state=floating
bspc rule -a '*:gpick' state=floating
bspc rule -a '*:microsoft teams - preview' state=floating

############ Program settings #################
picom --config $HOME/.config/picom/picom.conf &
dunst &
noisetorch -i &
keepassxc &

############ Other Settings #################
xsetroot -cursor_name left_ptr &
